name: Clear UK Number 1 Playlist (Manual)

on:
  workflow_dispatch:
    inputs:
      debug:
        description: "Dry-run (do not actually clear when true)"
        type: boolean
        default: false
        required: false

permissions:
  contents: write

jobs:
  clear:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || pip install spotipy pandas beautifulsoup4 requests lxml

      - name: Clear (ACTION=clear)
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          ACTION: clear
          DEBUG: ${{ inputs.debug || 'false' }}
        run: python script.py

      - name: Commit updated outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add added_tracks.json not_found.json track_cache.json
          git commit -m "Manual clear: reset outputs" || echo "No changes to commit"
          git push
