name: Update UK Number 1 Playlist

on:
  schedule:
    - cron: "0 9 * * 5" # Every Friday at 9am UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install spotipy pandas beautifulsoup4 requests lxml

      - name: Run script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIFY_PLAYLIST_ID: ${{ secrets.SPOTIFY_PLAYLIST_ID }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          DEBUG: "true"
        run: python script.py

      - name: Commit updated track list
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add added_tracks.json
          git commit -m "Update added tracks" || echo "No changes to commit"
          git push
